version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: nanoninja/php-fpm:latest
    volumes:
      - ./www:/var/www/html
    extra_hosts:
      - "mysql:host.docker.internal"